import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){try{var storageKey='tillwad-theme';var stored=window.localStorage.getItem(storageKey);var prefersLight=window.matchMedia('(prefers-color-scheme: light)').matches;var theme=stored==='light'||stored==='dark'?stored:(prefersLight?'light':'dark');var root=document.documentElement;var body=document.body;root.classList.toggle('dark', theme==='dark');if(body){body.classList.toggle('dark', theme==='dark');}window.localStorage.setItem(storageKey, theme);}catch(e){}})();`,
          }}
        />
        {children}
      </body>
    </html>
  );
}
